/**
 * Курируемые реэкспорты Lucide с префиксом `AprilIcon*`.
 * Добавляйте новые символы только по согласованию с DS, чтобы набор оставался согласованным между продуктами.
 */
export {
  LayoutDashboard as AprilIconDashboard,
  Folder as AprilIconFolder,
  Users as AprilIconUsers,
  FileText as AprilIconFileText,
  Settings as AprilIconSettings,
  ChevronRight as AprilIconChevronRight,
  ChevronLeft as AprilIconChevronLeft,
  PanelLeft as AprilIconPanelLeft,
  Search as AprilIconSearch,
  Plus as AprilIconPlus,
  Pencil as AprilIconPencil,
  Edit as AprilIconEdit,
  Trash2 as AprilIconTrash,
  Copy as AprilIconCopy,
  MoreHorizontal as AprilIconMoreHorizontal,
  RotateCcw as AprilIconRotateCcw,
  Send as AprilIconSend,
  Check as AprilIconCheck,
  X as AprilIconClose,
  Info as AprilIconInfo,
  CheckCircle2 as AprilIconSuccess,
  AlertTriangle as AprilIconWarning,
  XCircle as AprilIconError,
  Bell as AprilIconBell,
  CircleHelp as AprilIconHelp,
  MessageSquare as AprilIconMessage,
  Mail as AprilIconMail,
  Lock as AprilIconLock,
  ClipboardList as AprilIconClipboardList,
  Braces as AprilIconBraces,
  Calendar as AprilIconCalendar,
  LogOut as AprilIconLogOut,
  User as AprilIconUser,
  Sun as AprilIconSun,
  Moon as AprilIconMoon,
} from 'lucide-react';
